"use client";

import Image from "next/image";
import { FormEvent, useEffect, useState } from "react";
import ImageUpload from "@/components/admin/ImageUpload";
import { useConfirmDialog } from "@/components/admin/ConfirmDialog";

const launchImageDimensions = { width: 1200, height: 800 };
type Launch = { _id: string; restaurantName: string; location: string; cuisine: string; launchYear: number; image: string; servicesProvided: string[]; status: "open" | "renovated" };
type Form = Omit<Launch, "_id" | "servicesProvided" | "status"> & { servicesProvided: string; status: Launch["status"] };
const emptyForm: Form = { restaurantName: "", location: "", cuisine: "", launchYear: "" as unknown as number, image: "/assets/images/gallery-1.jpg", servicesProvided: "", status: "open" };

export default function AdminLaunches() {
  const confirm = useConfirmDialog();
  const [launches, setLaunches] = useState<Launch[]>([]);
  const [form, setForm] = useState<Form>(emptyForm);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const load = async () => { const response = await fetch("/api/admin/launches", { credentials: "include", cache: "no-store" }); const result = await response.json(); if (response.ok) setLaunches(result.launches || []); else setMessage(result.error || "دریافت راه‌اندازی‌ها ناموفق بود"); };
  useEffect(() => { load(); }, []);
  const update = (field: keyof Form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(""); const body = { ...form, launchYear: Number(form.launchYear), servicesProvided: form.servicesProvided.split(",").map((item) => item.trim()).filter(Boolean) }; const response = await fetch("/api/admin/launches", { method: editingId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify(editingId ? { ...body, id: editingId } : body) }); const result = await response.json(); setSaving(false); if (!response.ok) { setMessage(result.error || "ذخیره راه‌اندازی ناموفق بود"); return; } setLaunches((current) => editingId ? current.map((item) => item._id === editingId ? result.launch : item) : [result.launch, ...current]); setMessage(editingId ? "راه‌اندازی ویرایش شد" : "راه‌اندازی جدید ثبت شد"); setForm(emptyForm); setEditingId(null); setShowForm(false); };
  const edit = (launch: Launch) => { setEditingId(launch._id); setForm({ restaurantName: launch.restaurantName, location: launch.location, cuisine: launch.cuisine, launchYear: launch.launchYear, image: launch.image, servicesProvided: launch.servicesProvided.join(", "), status: launch.status }); setShowForm(true); setMessage(""); };
  const remove = async (id: string) => { if (!await confirm({ title: "حذف راه‌اندازی", description: "این مورد حذف می‌شود و امکان بازگردانی آن وجود ندارد." })) return; const response = await fetch("/api/admin/launches", { method: "DELETE", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ id }) }); if (response.ok) setLaunches((current) => current.filter((item) => item._id !== id)); else { const result = await response.json(); setMessage(result.error || "حذف ناموفق بود"); } };
  return <div className="space-y-6"><section className="rounded-lg bg-white p-6 shadow"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-gray-800">راه‌اندازی‌ها</h1><p className="mt-1 text-sm text-gray-500">کارت‌های این بخش مستقل از مدیریت پروژه‌ها و به‌صورت دستی مدیریت می‌شوند.</p></div><button onClick={() => { setShowForm((value) => !value); setEditingId(null); setForm(emptyForm); }} className="rounded bg-blue-600 px-4 py-2 font-bold text-white">{showForm ? "بستن فرم" : "+ راه‌اندازی جدید"}</button></div>{showForm && <LaunchForm form={form} update={update} onSubmit={save} saving={saving} editing={Boolean(editingId)} />}{message && <p className="mt-4 rounded bg-blue-50 p-3 text-sm text-blue-800">{message}</p>}<div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{launches.map((launch) => <article key={launch._id} className="overflow-hidden rounded-lg border border-gray-200 bg-gray-50"><div className="relative aspect-3/2 bg-gray-100"><Image src={launch.image} alt={launch.restaurantName} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-contain" /></div><div className="p-4"><div className="flex items-start justify-between gap-2"><h2 className="font-bold text-gray-800">{launch.restaurantName}</h2><span className="rounded-full bg-green-100 px-2 py-1 text-xs text-green-800">{launch.status === "open" ? "فعال" : "بازسازی‌شده"}</span></div><p className="mt-2 text-sm text-gray-600">{launch.location}</p><p className="text-sm text-gray-600">{launch.cuisine} | {launch.launchYear}</p><div className="mt-3 flex flex-wrap gap-1">{launch.servicesProvided.map((service) => <span key={service} className="rounded-full bg-gray-200 px-2 py-1 text-xs text-gray-700">{service}</span>)}</div><div className="mt-4 flex gap-3"><button onClick={() => edit(launch)} className="text-blue-600">ویرایش</button><button onClick={() => remove(launch._id)} className="text-red-600">حذف</button></div></div></article>)}</div></section></div>;
}

function LaunchForm({ form, update, onSubmit, saving, editing }: { form: Form; update: (field: keyof Form, value: string) => void; onSubmit: (event: FormEvent) => void; saving: boolean; editing: boolean }) { const field = (label: string, key: keyof Form, type = "text") => <label className="text-sm font-semibold text-gray-700">{label}<input required={key !== "servicesProvided"} type={type} value={String(form[key])} onChange={(event) => update(key, event.target.value)} className="mt-1 block w-full rounded border border-gray-300 bg-white px-3 py-2 font-normal" /></label>; return <form onSubmit={onSubmit} className="mt-5 grid gap-4 rounded-lg border border-blue-100 bg-blue-50 p-4 sm:grid-cols-2">{field("نام رستوران", "restaurantName")}{field("موقعیت", "location")}{field("نوع غذا", "cuisine")}{field("سال راه‌اندازی", "launchYear", "number")}<ImageUpload label="تصویر راه‌اندازی" value={form.image} onChange={(value) => update("image", value)} recommendedDimensions={launchImageDimensions} />{field("خدمات با ویرگول جدا شود", "servicesProvided")}<label className="text-sm font-semibold text-gray-700">وضعیت<select value={form.status} onChange={(event) => update("status", event.target.value)} className="mt-1 block w-full rounded border border-gray-300 bg-white px-3 py-2 font-normal"><option value="open">فعال</option><option value="renovated">بازسازی‌شده</option></select></label><div className="flex items-end"><button disabled={saving} className="rounded bg-green-600 px-5 py-2 font-bold text-white disabled:opacity-50">{saving ? "در حال ذخیره..." : editing ? "ذخیره ویرایش" : "ثبت راه‌اندازی"}</button></div></form>; }
